name: sudoku_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  get_it: ^8.2.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/cats/
    - assets/halloween/
    - assets/sea_animals/
  fonts:
    - family: Overbit Shadow
      fonts:
        - asset: assets/Overbit-Shadow.otf
    - family: Overbit Regular
      fonts:
        - asset: assets/Overbit-Regular.otf
    - family: Brick Sans
      fonts:
        - asset: assets/NTBrickSans.otf

import_sorter:
  emojis: true
  comments: false